version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=lectio-divina-db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    volumes:
      - ./src:/app/
    restart: unless-stopped

    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - NODE_PORT=$NODE_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_DATABASE
      - POSTGRES_PORT=$POSTGRES_PORT
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
